name: deployment
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploying App Container
        run: |
          cd /deployment/go-app-deployment/actions-runner/go-app/sample-go-app/sample-go-app
          docker stop GoApp && docker rm GoApp
          docker image rmi -f go-app
          docker build -t go-app .
          docker run -d --name GoApp -p 8081:8081 go-app
          docker ps
